extends: "spectral:oas"

rules:
  info-contact: off
  contact-properties: off
  info-description: off
  info-license: off
  license-url: off
  operation-description: off
  operation-tag-defined: off
  operation-operationId: off
  oas3-api-servers: off
  oas3-unused-component: off
  openapi-tags: off
  
  path-camel-case:
    description: "Path segments should be camelCase"
    message: "Path '{{path}}' is not camelCase"
    severity: error
    given: $.paths[?(!@property.match(/\{[^}]+\}/) && @['x-removed'] != true)]~
    then:
      function: casing
      functionOptions:
        type: camel
        separator:
          char: "/"
          allowLeading: true

  parameter-naming-camelCase:
    description: "Parameters (path, query, header) must use camelCase"
    message: "Parameter name '{{name}}' is not camelCase"
    severity: error
    given:
      - $.paths[*][*].parameters[*]          # operation-level params
      - $.paths[*].parameters[*]             # path-level params
      - $.components.parameters[*]           # reusable params
    then:
      field: name
      function: pattern
      functionOptions:
        match: '^[a-z][a-zA-Z0-9]*$'

  path-versioning:
    description: "Paths must include a major version (e.g. /v1/...)"
    message: "Path '{path}' must start with /v<number>/"
    severity: error
    given: "$.paths"
    then:
      field: "@key"
      function: pattern
      functionOptions:
        match: '^/v[0-9]+/.*$'

  tag-pascal-case:
    description: "Tags should be PascalCase"
    message: "Tag '{{value}}' is not PascalCase"
    severity: warn
    given: $.paths.*.*.tags[*]
    then:
      function: casing
      functionOptions:
        type: pascal

  require-json-body:
    description: "Responses must include media-type application/json (other media types may also be present)"
    message: "Response for code does not include media-type application/json"
    severity: error
    formats:
      - oas3
    given:
      - $.paths[*][*].responses[*].content
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          required:
            - application/json

  # # Alternative: 2xx JSON responses must have top-level code + data were required field isn't required, just checks presence
  response-envelope-has-code-and-data:
    description: "2xx JSON responses must have top-level 'code' and 'data' properties"
    message: "2xx JSON response must define top-level 'code' and 'data' properties in its JSON schema"
    severity: error
    formats:
      - oas3
    resolved: true
    given:
      - >-
        $.paths[*][*].responses[?(@property >= '200' && @property < '300' && @property != '204')]
          .content["application/json"].schema
    then:
      - field: properties.code
        function: truthy
      - field: properties.data
        function: truthy

  # Rule 2: Check CommonResponse has code property
  common-response-has-code:
    description: "CommonResponse must have 'code' property"
    message: "Schema '{{property}}' must define a 'code' property"
    severity: error
    given: $.components.schemas[?(@property.match(/CommonResponse$/))].properties
    then:
      field: code
      function: truthy

  # Rule 3: Check CommonResponse has data property
  common-response-has-data:
    description: "CommonResponse must have 'data' property"
    message: "Schema '{{property}}' must define a 'data' property"
    severity: error
    given: $.components.schemas[?(@property.match(/CommonResponse$/))].properties
    then:
      field: data
      function: truthy

  # Rule 4: 204 responses must not have a body
  no-content-response-no-body:
    description: "204 responses must not have a response body"
    message: "Response code '204' must not have a response body"
    severity: error
    given: $.paths[*][*].responses['204'].content
    then:
      function: falsy