name: API Governance Engine

# 1. --- Define Inputs ---
on:
  workflow_call:
    inputs:
      swagger_path:
        required: true
        type: string
        description: "Path to the swagger file in the spoke repo (e.g. swagger.yaml)"
      baseline_filename:
        required: true
        type: string
        description: "Name of the baseline file in the Release (e.g. javatest-legacy.yaml)"
      baseline_version:
        required: false
        type: string
        default: 'baselines-v1'
        description: "The Release Tag to download from"

jobs:
  governance-engine:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to download releases
    
    steps:
      # ---------------------------------------------------------
      # 1. Checkout Repositories
      # ---------------------------------------------------------
      - name: Checkout Spoke Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for history

      - name: Checkout Governance Hub
        uses: actions/checkout@v4
        with:
          repository: KushalBang456/API-Governance-POC
          path: governance-hub

      # ---------------------------------------------------------
      # 2. Setup Environment (MISSING IN YOUR SNIPPET)
      # ---------------------------------------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # ---------------------------------------------------------
      # 3. Install Dependencies
      # ---------------------------------------------------------
      - name: Install Dependencies
        run: |
          npm install -g openapi-diff @stoplight/spectral-cli
          pip install PyYAML

      # ---------------------------------------------------------
      # 4. Prepare Specs (Extract HEAD and TARGET versions)
      # ---------------------------------------------------------
      - name: Prepare Specs
        run: |
          echo "📍 Processing Swagger: ${{ inputs.swagger_path }}"
          
          # A. Capture Filename & Extension
          INPUT_FILE="${{ inputs.swagger_path }}"
          EXT="${INPUT_FILE##*.}"
          
          # B. Determine Target Branch (Dynamic)
          TARGET_BRANCH="${{ github.base_ref }}"
          if [ -z "$TARGET_BRANCH" ]; then
            TARGET_BRANCH="main"
            echo "⚠️ Manual Trigger detected. Defaulting target to 'main'."
          fi

          # 1. Get HEAD version (Current file)
          if [ -f "$INPUT_FILE" ]; then
             cp "$INPUT_FILE" "swagger_head.$EXT"
          else
             echo "❌ Error: Swagger file not found at $INPUT_FILE"
             exit 1
          fi
          
          # 2. Get TARGET version (Base Branch)
          echo "Fetching version from origin/$TARGET_BRANCH..."
          git show "origin/$TARGET_BRANCH:$INPUT_FILE" > "swagger_main.$EXT"
          
          echo "✅ Extracted Head and Main specs."

      # ---------------------------------------------------------
      # 5. Download Baseline
      # ---------------------------------------------------------
      - name: ⬇️ Download Baseline from GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching ${{ inputs.baseline_filename }} from tag ${{ inputs.baseline_version }}..."
          gh release download ${{ inputs.baseline_version }} \
            --repo KushalBang456/API-Governance-POC \
            --pattern "${{ inputs.baseline_filename }}"

      # ---------------------------------------------------------
      # 6. Generate Diff
      # ---------------------------------------------------------
      - name: Generate Diff
        run: |
          # Re-detect extension
          INPUT="${{ inputs.swagger_path }}"
          EXT="${INPUT##*.}"
          
          echo "🔍 Generating diff between swagger_main.$EXT and swagger_head.$EXT..."
          openapi-diff "swagger_main.$EXT" "swagger_head.$EXT" --format json > diff.json

      # ---------------------------------------------------------
      # 7. Run Logic (Python)
      # ---------------------------------------------------------
      - name: Generate Partial Spec
        run: |
          python governance-hub/scripts/generate_partial_spec.py "${{ inputs.baseline_filename }}"

      # ---------------------------------------------------------
      # 8. Linting (Strict)
      # ---------------------------------------------------------
      - name: 🛑 Strict Lint (Blocks PR)
        run: |
          npx spectral lint partial_spec.json \
            --ruleset governance-hub/.spectral.yaml \
            --format stylish

      # ---------------------------------------------------------
      # 9. Linting (Advisory)
      # ---------------------------------------------------------
      - name: ⚠️ Advisory Lint (Tech Debt)
        continue-on-error: true
        run: |
          INPUT="${{ inputs.swagger_path }}"
          EXT="${INPUT##*.}"
          
          npx spectral lint "swagger_head.$EXT" \
            --ruleset governance-hub/.spectral-warn.yaml \
            --format stylish